### ISSUE TITLE
Share with same CSS as Theme

### ISSUE THREAD

**Issue by AlexMontesCS** [Ellpeck/ObsidianJustSharePlease#15]
Would be nice if when shared the same styling is applied to the published site as in my editor. I can make a PR when I have some time

**Comment by Ellpeck** [comment]
Hi! There are no plans for applying your Obsidian theme's or snippets' styling, and it's not something I'm interested in being part of JSP at the moment, sorry :( 

It's a core part of JSP's design to upload the text and images only, and no other data or content. That's why I made the decision to have notes uploaded as Markdown rather than HTML or some other "exported" format.
